name: build

on:
  push:
    branches: [ master, linux-ci-cd ]
  pull_request:
    branches: [ master, linux-ci-cd ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: yarn
    - name: Prepack from TypeScript/ES6 source
      run: yarn prepack
    - name: Launch tests
      run: yarn test

  live-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: yarn global add @tommywalkie/cli
    - name: Try a sample command
      run: excalidraw-cli --help

